### ISSUE TITLE
Create trusted image CRD

### ISSUE THREAD

**Issue by JorritSalverda** [estafette/estafette-ci-operator#2]
Support a trustedimage CRD with the following api version and kind

```yaml
apiVersion: ci.estafette.io/v1
kind: trustedimage
```

And the following fields in the spec:

```yaml
path: <string, required and needs to be unique>
runPrivileged: <bool, optional>
runDocker: <bool, optional>
allowCommands: <bool, optional>
injectedCredentialTypes: <[]string, optional>
whitelistedPipelines: <string, optional>
```

The path is a path to a container image including repository, but excluding the tag.

See https://github.com/estafette/estafette-ci-contracts/blob/master/config.go#L81-L89
